.Dd September 18, 2022
.Dt APINT 1
.Sh NAME
.Nm apint
.Nd primitive paint application for X
.Sh SYNOPSIS
.Nm
.Op Fl fhv
.Op Fl l Ar file
.Sh DESCRIPTION
The
.Nm
application lets you draw over an empty canvas or one loaded from a png file.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
start in fullscreen mode
.It Fl h
show usage
.It Fl v
display the program version
.It Fl l
load png file
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It draw over a freshly taken screenshot
apint -f -l $(xscreenshot -p -d $(mktemp -d))
.El
.Sh SEE ALSO
.Xr X 7
.Xr png 5
.Xr xscreenshot 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/apint/issues
