.Dd March 25, 2023
.Dt APINT 1
.Sh NAME
.Nm apint
.Nd primitive paint application for X
.Sh SYNOPSIS
.Nm
.Op Fl fhv
.Op Fl l Ar file
.Op Fl W Ar width
.Op Fl H Ar height
.Sh DESCRIPTION
The
.Nm
application lets you draw over an empty canvas or one loaded from a png file.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
start in fullscreen mode
.It Fl h
show usage
.It Fl v
display the program version
.It Fl l
load canvas from png file
.It Fl W
create a canvas of that width
.It Fl H
create a canvas of that height
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It draw over a freshly taken screenshot
apint -f -l $(xscreenshot -p -d $(mktemp -d))
.El
.Sh KEYBOARD BINDINGS
.Bl -tag -width indent
.It Ctrl+s
Save the current canvas to a file.
.It Ctrl+z
Undo (If compiled with history support).
.It Ctrl+y
Redo (If compiled with history support).
.It r
Set color to red.
.It g
Set color to green.
.It b
Set color to blue.
.It w
Set color to white.
.It q
Set color to black.
.It o
Set color to orange.
.It y
Set color to yellow.
.It f
Set color to fuchsia.
.It t
Set color to teal.
.It c
Set color to cream.
.El
.Sh MOUSE BINDINGS
.Bl -tag -width indent
.It Left Mouse Button
Draw.
.It Right Mouse Button
Open the color selection tool.
.It Middle Mouse Button
Move around.
.It Scroll Up/Down
Change brush size.
.El
.Sh SEE ALSO
.Xr X 7
.Xr zinc 1
.Xr png 5
.Xr xscreenshot 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/apint/issues
