.TH APINT 1 "July 27, 2022"
.SH NAME
apint \- primitive paint application for X.
.SH SYNOPSIS
\fBapint\fP [ -hv ]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
display the program version
.SH EXIT STATUS
.TP
\fB0\fR
the program terminated successfully
.TP
\fB1\fR
an error occurred
.SH AUTHOR
Written by alpheratz0.
.SH COPYRIGHT
Copyright \(co 2022 <alpheratz99@protonmail.com>
.br
License GPLv2.0: GNU GPL version 2.0 <https://gnu.org/licenses/old-licenses/gpl-2.0.en.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
https://github.com/alpheratz0/apint/issues
